version: 2.1

orbs:
  semantic-release: trustedshops-public/semantic-release@6.0.0
  

executors:
  python:
    docker:
      - image: python:3.8.11-alpine3.14 # the primary container, where your job's commands are run

commands:
  # A command named `echo` that runs the `echo` command
  listar:
    parameters:
      message:
        type: string
        default: -l
    steps:
      - run: ls << parameters.message >>

jobs:
  test-job:
    executor: python # use the `node` executor defined above
    steps:
      - add_ssh_keys:
          fingerprints:
            - "48:c5:94:65:ce:3f:b3:63:bc:d0:03:f7:99:22:6b:5c"    
      - checkout # check out the code in the project directory
      - run: ls -l  # run the `echo` command
      - listar: 
          message: -la
      - run: pip3.8 install virtualenv  
      - run: python3.8 -m venv venv  
      - run: source venv/bin/activate 
      - run: pip3.8 install -r requirements.txt 
      - run: pytest -m "not integtest" --cov --cov-report=html  
      - semantic-release/create_changelog_config_github

workflows:
  my-workflow:
    jobs:
      - test-job
  
           

